=== Deadmau8772/yast-autoinstallation/doc/profile.dtd
<!ELEMENT from_header (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ATTLIST format config:type CDATA #IMPLIED>
<!ELEMENT wireless_nwid (#PCDATA)>
<!ELEMENT aliases (#PCDATA | alias)*>
<!ATTLIST aliases config:type CDATA #IMPLIED>
<!ELEMENT nfs_exports (#PCDATA | nfs_export)*>
<!ATTLIST nfs_exports config:type CDATA #IMPLIED>
<!ELEMENT filename (#PCDATA)>
<!ELEMENT warnings (#PCDATA | log | show | timeout)*>
<!ELEMENT address (#PCDATA)>
<!ELEMENT lastlog_enab (#PCDATA)>
<!ELEMENT encryption (#PCDATA)>
<!ELEMENT option_blank (#PCDATA)>
<!ATTLIST option_blank config:type CDATA #IMPLIED>
<!ELEMENT networking (#PCDATA | dns | interfaces | routing)*>
<!ELEMENT dhcp_resolv (#PCDATA)>
<!ATTLIST dhcp_resolv config:type CDATA #IMPLIED>
<!ELEMENT nis_other_domain (#PCDATA | nis_broadcast | nis_domain | nis_servers)*>
<!ELEMENT server_path (#PCDATA)>
<!ELEMENT faillog_enab (#PCDATA)>
<!ELEMENT hostname (#PCDATA)>
<!ELEMENT configure (#PCDATA | ldap | mail | networking | nfs | nfs_server | nis | nisplus | printer | scripts | security | sound | sysconfig | users | x11)*>
<!ELEMENT device (#PCDATA)>
<!ELEMENT ldap_tls (#PCDATA)>
<!ATTLIST ldap_tls config:type CDATA #IMPLIED>
<!ELEMENT report (#PCDATA | errors | messages | warnings)*>
<!ELEMENT nfs_entry (#PCDATA | mount_point | nfs_options | server_path)*>
<!ELEMENT destinations (#PCDATA)>
<!ELEMENT addon (#PCDATA)>
<!ELEMENT gateway (#PCDATA)>
<!ELEMENT destination (#PCDATA)>
<!ELEMENT profile_port (#PCDATA)>
<!ELEMENT ldap_v2 (#PCDATA)>
<!ATTLIST ldap_v2 config:type CDATA #IMPLIED>
<!ELEMENT pass_min_len (#PCDATA)>
<!ELEMENT listen_remote (#PCDATA)>
<!ATTLIST listen_remote config:type CDATA #IMPLIED>
<!ELEMENT uid_max (#PCDATA)>
<!ELEMENT mouse (#PCDATA | id)*>
<!ELEMENT color_depth (#PCDATA)>
<!ATTLIST color_depth config:type CDATA #IMPLIED>
<!ELEMENT chroot-scripts (#PCDATA | script)*>
<!ATTLIST chroot-scripts config:type CDATA #IMPLIED>
<!ELEMENT ipaddr (#PCDATA)>
<!ELEMENT nisplus_server (#PCDATA)>
<!ELEMENT fetchmail_entry (#PCDATA | local_user | password | protocol | remote_user | server)*>
<!ELEMENT nis (#PCDATA | nis_broadcast | nis_broken_server | nis_domain | nis_local_only | nis_options | nis_other_domains | nis_servers | start_autofs | start_nis)*>
<!ELEMENT type (#PCDATA)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT ip (#PCDATA)>
<!ELEMENT pre-scripts (#PCDATA | script)*>
<!ATTLIST pre-scripts config:type CDATA #IMPLIED>
<!ELEMENT virtual_users (#PCDATA | virtual_user)*>
<!ATTLIST virtual_users config:type CDATA #IMPLIED>
<!ELEMENT profile (#PCDATA | configure | install)*>
<!ELEMENT port (#PCDATA)>
<!ELEMENT obscure_checks_enab (#PCDATA)>
<!ELEMENT allowed (#PCDATA | allowed_clients)*>
<!ATTLIST allowed config:type CDATA #IMPLIED>
<!ELEMENT drive (#PCDATA | device | initialize | partitions | use)*>
<!ELEMENT serverdir (#PCDATA)>
<!ELEMENT start_autofs (#PCDATA)>
<!ATTLIST start_autofs config:type CDATA #IMPLIED>
<!ELEMENT id (#PCDATA)>
<!ELEMENT start_ldap (#PCDATA)>
<!ATTLIST start_ldap config:type CDATA #IMPLIED>
<!ELEMENT sysconfig_entry (#PCDATA | sysconfig_key | sysconfig_path | sysconfig_value)*>
<!ELEMENT pass_max_len (#PCDATA)>
<!ELEMENT base (#PCDATA)>
<!ELEMENT cwd_in_root_path (#PCDATA)>
<!ELEMENT opt_format (#PCDATA | option_blank | option_str | option_value)*>
<!ELEMENT wireless_mode (#PCDATA)>
<!ELEMENT timeout (#PCDATA)>
<!ATTLIST timeout config:type CDATA #IMPLIED>
<!ELEMENT nameserver (#PCDATA)>
<!ELEMENT install (#PCDATA | bootloader | general | init | partitioning | report | software)*>
<!ELEMENT server (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT console_shutdown (#PCDATA)>
<!ELEMENT max_hsync (#PCDATA)>
<!ATTLIST max_hsync config:type CDATA #IMPLIED>
<!ELEMENT user (#PCDATA | encrypted | user_password | username)*>
<!ELEMENT sysconfig_key (#PCDATA)>
<!ELEMENT dhclient_set_down_link (#PCDATA)>
<!ELEMENT reboot (#PCDATA)>
<!ATTLIST reboot config:type CDATA #IMPLIED>
<!ELEMENT cups-state (#PCDATA)>
<!ELEMENT ldap_domain (#PCDATA)>
<!ELEMENT snd_enable (#PCDATA)>
<!ELEMENT nfs_options (#PCDATA)>
<!ELEMENT ldap (#PCDATA | ldap_domain | ldap_server | ldap_tls | ldap_v2 | start_ldap)*>
<!ELEMENT mount_point (#PCDATA)>
<!ELEMENT monitor_device (#PCDATA)>
<!ELEMENT pass_warn_age (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT masquerade_other_domains (#PCDATA | domain)*>
<!ATTLIST masquerade_other_domains config:type CDATA #IMPLIED>
<!ELEMENT security (#PCDATA | console_shutdown | cwd_in_root_path | displaymanager_remote_access | encryption | fail_delay | faillog_enab | gid_max | gid_min | kdm_shutdown | lastlog_enab | obscure_checks_enab | pass_max_days | pass_max_len | pass_min_days | pass_min_len | pass_warn_age | passwd_use_cracklib | permission_security | run_updatedb_as | uid_max | uid_min)*>
<!ELEMENT extra_packages (#PCDATA | package_location | packages)*>
<!ELEMENT max_vsync (#PCDATA)>
<!ATTLIST max_vsync config:type CDATA #IMPLIED>
<!ELEMENT protocol (#PCDATA)>
<!ELEMENT mountpoint (#PCDATA)>
<!ELEMENT wireless_essid (#PCDATA)>
<!ELEMENT gid_max (#PCDATA)>
<!ELEMENT lba_support (#PCDATA)>
<!ATTLIST lba_support config:type CDATA #IMPLIED>
<!ELEMENT connection_type (#PCDATA)>
<!ATTLIST connection_type config:type CDATA #IMPLIED>
<!ELEMENT filesystem (#PCDATA)>
<!ATTLIST filesystem config:type CDATA #IMPLIED>
<!ELEMENT default (#PCDATA)>
<!ELEMENT nfs (#PCDATA | nfs_entry)*>
<!ATTLIST nfs config:type CDATA #IMPLIED>
<!ELEMENT general (#PCDATA | clock | keyboard | language | mode | mouse)*>
<!ELEMENT alias (#PCDATA | alias | destinations)*>
<!ELEMENT nis_broadcast (#PCDATA)>
<!ATTLIST nis_broadcast config:type CDATA #IMPLIED>
<!ELEMENT profile_protocol (#PCDATA)>
<!ELEMENT mail (#PCDATA | aliases | connection_type | fetchmail | from_header | listen_remote | local_domains | masquerade_other_domains | masquerade_users | mta | outgoing_mail_server | use_amavis | virtual_users)*>
<!ELEMENT info_file (#PCDATA)>
<!ELEMENT virtual_user (#PCDATA | alias | destinations)*>
<!ELEMENT partition_id (#PCDATA)>
<!ATTLIST partition_id config:type CDATA #IMPLIED>
<!ELEMENT searchlist (#PCDATA | search)*>
<!ATTLIST searchlist config:type CDATA #IMPLIED>
<!ELEMENT kernel_parameters (#PCDATA)>
<!ELEMENT ff (#PCDATA)>
<!ATTLIST ff config:type CDATA #IMPLIED>
<!ELEMENT confirm (#PCDATA)>
<!ATTLIST confirm config:type CDATA #IMPLIED>
<!ELEMENT dhcp_hostname (#PCDATA)>
<!ATTLIST dhcp_hostname config:type CDATA #IMPLIED>
<!ELEMENT linear (#PCDATA)>
<!ATTLIST linear config:type CDATA #IMPLIED>
<!ELEMENT password (#PCDATA)>
<!ELEMENT nis_domain (#PCDATA)>
<!ELEMENT display (#PCDATA | bandwidth | height | max_hsync | max_vsync | min_hsync | min_vsync | width)*>
<!ELEMENT netmask (#PCDATA)>
<!ELEMENT interactive_boot (#PCDATA)>
<!ATTLIST interactive_boot config:type CDATA #IMPLIED>
<!ELEMENT masquerade_users (#PCDATA | masquerade_user)*>
<!ATTLIST masquerade_users config:type CDATA #IMPLIED>
<!ELEMENT allowed_clients (#PCDATA)>
<!ELEMENT errors (#PCDATA | log | show | timeout)*>
<!ELEMENT resolution (#PCDATA)>
<!ELEMENT forceboot (#PCDATA)>
<!ATTLIST forceboot config:type CDATA #IMPLIED>
<!ELEMENT mount (#PCDATA)>
<!ELEMENT monitor (#PCDATA | display | monitor_device | monitor_vendor)*>
<!ELEMENT startmode (#PCDATA)>
<!ELEMENT sysconfig_value (#PCDATA)>
<!ELEMENT uid_min (#PCDATA)>
<!ELEMENT routing (#PCDATA | ip_forward | routes)*>
<!ELEMENT post-scripts (#PCDATA | script)*>
<!ATTLIST post-scripts config:type CDATA #IMPLIED>
<!ELEMENT autoinstall (#PCDATA)>
<!ATTLIST autoinstall config:type CDATA #IMPLIED>
<!ELEMENT printer (#PCDATA | default | printcap)*>
<!ELEMENT opt_hash (#PCDATA | option_blank | option_str | option_value)*>
<!ELEMENT textmode (#PCDATA)>
<!ATTLIST textmode config:type CDATA #IMPLIED>
<!ELEMENT start_nis (#PCDATA)>
<!ATTLIST start_nis config:type CDATA #IMPLIED>
<!ELEMENT snd_index (#PCDATA)>
<!ELEMENT permission_security (#PCDATA)>
<!ELEMENT software (#PCDATA | addons | base | extra_packages | packages)*>
<!ELEMENT location (#PCDATA)>
<!ELEMENT ip_forward (#PCDATA)>
<!ATTLIST ip_forward config:type CDATA #IMPLIED>
<!ELEMENT bootproto (#PCDATA)>
<!ELEMENT script (#PCDATA | filename | interpreter | source)*>
<!ELEMENT crypt_key (#PCDATA)>
<!ELEMENT sysconfig (#PCDATA | sysconfig_entry)*>
<!ATTLIST sysconfig config:type CDATA #IMPLIED>
<!ELEMENT keyboard (#PCDATA | keymap)*>
<!ELEMENT interfaces (#PCDATA | interface)*>
<!ATTLIST interfaces config:type CDATA #IMPLIED>
<!ELEMENT nis_options (#PCDATA)>
<!ELEMENT width (#PCDATA)>
<!ATTLIST width config:type CDATA #IMPLIED>
<!ELEMENT wireless_nick (#PCDATA)>
<!ELEMENT wireless_key (#PCDATA)>
<!ELEMENT fetchmail (#PCDATA | fetchmail_entry)*>
<!ATTLIST fetchmail config:type CDATA #IMPLIED>
<!ELEMENT network (#PCDATA)>
<!ELEMENT displaymanager_remote_access (#PCDATA)>
<!ELEMENT profile_location (#PCDATA)>
<!ELEMENT passwd_use_cracklib (#PCDATA)>
<!ELEMENT remote_user (#PCDATA)>
<!ELEMENT keymap (#PCDATA)>
<!ELEMENT interpreter (#PCDATA)>
<!ELEMENT modules_conf (#PCDATA | module_conf)*>
<!ATTLIST modules_conf config:type CDATA #IMPLIED>
<!ELEMENT show (#PCDATA)>
<!ATTLIST show config:type CDATA #IMPLIED>
<!ELEMENT options (#PCDATA | snd_enable | snd_index | snd_pcm_channels)*>
<!ELEMENT clock (#PCDATA | timezone | utc)*>
<!ELEMENT configure_x11 (#PCDATA)>
<!ATTLIST configure_x11 config:type CDATA #IMPLIED>
<!ELEMENT nis_broken_server (#PCDATA)>
<!ATTLIST nis_broken_server config:type CDATA #IMPLIED>
<!ELEMENT route (#PCDATA | destination | gateway | netmask | device)*>
<!ELEMENT use_amavis (#PCDATA)>
<!ATTLIST use_amavis config:type CDATA #IMPLIED>
<!ELEMENT nisplus (#PCDATA | nisplus_domain | nisplus_password | nisplus_server | start_autofs | start_nisplus)*>
<!ELEMENT wireless (#PCDATA)>
<!ELEMENT lprng-state (#PCDATA)>
<!ELEMENT package_location (#PCDATA)>
<!ELEMENT pass_max_days (#PCDATA)>
<!ELEMENT sysconfig_path (#PCDATA)>
<!ELEMENT printcap_entry (#PCDATA | cups-state | ff | info | location | lprng-state | name | raw | type | uri)*>
<!ELEMENT nisplus_password (#PCDATA)>
<!ELEMENT volume_settings (#PCDATA | volume_entry)*>
<!ATTLIST volume_settings config:type CDATA #IMPLIED>
<!ELEMENT initialize (#PCDATA)>
<!ATTLIST initialize config:type CDATA #IMPLIED>
<!ELEMENT activate (#PCDATA)>
<!ATTLIST activate config:type CDATA #IMPLIED>
<!ELEMENT addons (#PCDATA | addon)*>
<!ATTLIST addons config:type CDATA #IMPLIED>
<!ELEMENT partitions (#PCDATA | partition)*>
<!ATTLIST partitions config:type CDATA #IMPLIED>
<!ELEMENT run_updatedb_as (#PCDATA)>
<!ELEMENT ldap_server (#PCDATA)>
<!ELEMENT mode (#PCDATA | confirm | forceboot | interactive_boot | reboot)*>
<!ELEMENT printcap (#PCDATA | printcap_entry)*>
<!ATTLIST printcap config:type CDATA #IMPLIED>
<!ELEMENT unique_key (#PCDATA)>
<!ELEMENT partition (#PCDATA | crypt_fs | crypt_key | filesystem | format | fs_options | mount | partition_id | size)*>
<!ELEMENT instmode (#PCDATA)>
<!ELEMENT log (#PCDATA)>
<!ATTLIST log config:type CDATA #IMPLIED>
<!ELEMENT enable_3d (#PCDATA)>
<!ATTLIST enable_3d config:type CDATA #IMPLIED>
<!ELEMENT package (#PCDATA)>
<!ELEMENT utc (#PCDATA)>
<!ATTLIST utc config:type CDATA #IMPLIED>
<!ELEMENT nisplus_domain (#PCDATA)>
<!ELEMENT nis_local_only (#PCDATA)>
<!ATTLIST nis_local_only config:type CDATA #IMPLIED>
<!ELEMENT module_conf (#PCDATA | alias | model | module | options | unique_key)*>
<!ELEMENT nis_other_domains (#PCDATA | nis_other_domain)*>
<!ATTLIST nis_other_domains config:type CDATA #IMPLIED>
<!ELEMENT raw (#PCDATA)>
<!ATTLIST raw config:type CDATA #IMPLIED>
<!ELEMENT bootloader (#PCDATA | activate | kernel_parameters | lba_support | linear | location)*>
<!ELEMENT gid_min (#PCDATA)>
<!ELEMENT x11 (#PCDATA | color_depth | configure_x11 | display_manager | enable_3d | monitor | resolution)*>
<!ELEMENT monitor_vendor (#PCDATA)>
<!ELEMENT user_password (#PCDATA)>
<!ELEMENT encrypted (#PCDATA)>
<!ATTLIST encrypted config:type CDATA #IMPLIED>
<!ELEMENT snd_pcm_channels (#PCDATA)>
<!ELEMENT outgoing_mail_server (#PCDATA)>
<!ELEMENT start_nisplus (#PCDATA)>
<!ATTLIST start_nisplus config:type CDATA #IMPLIED>
<!ELEMENT fs_options (#PCDATA | opt_format | opt_hash)*>
<!ELEMENT messages (#PCDATA | log | show | timeout)*>
<!ELEMENT scripts (#PCDATA | chroot-scripts | post-scripts | pre-scripts)*>
<!ELEMENT timezone (#PCDATA)>
<!ELEMENT Master (#PCDATA)>
<!ATTLIST Master config:type CDATA #IMPLIED>
<!ELEMENT search (#PCDATA)>
<!ELEMENT use (#PCDATA)>
<!ELEMENT local_user (#PCDATA)>
<!ELEMENT mta (#PCDATA)>
<!ATTLIST mta config:type CDATA #IMPLIED>
<!ELEMENT fail_delay (#PCDATA)>
<!ELEMENT dns (#PCDATA | dhcp_hostname | dhcp_resolv | domain | hostname | nameservers | searchlist)*>
<!ELEMENT username (#PCDATA)>
<!ELEMENT module (#PCDATA)>
<!ELEMENT nfs_server (#PCDATA | nfs_exports | start_nfsserver)*>
<!ELEMENT option_value (#PCDATA)>
<!ELEMENT display_manager (#PCDATA)>
<!ELEMENT nis_servers (#PCDATA | nis_server)*>
<!ATTLIST nis_servers config:type CDATA #IMPLIED>
<!ELEMENT sound (#PCDATA | autoinstall | modules_conf | volume_settings)*>
<!ELEMENT routes (#PCDATA | route)*>
<!ATTLIST routes config:type CDATA #IMPLIED>
<!ELEMENT masquerade_user (#PCDATA | address | user)*>
<!ELEMENT nis_server (#PCDATA)>
<!ELEMENT local_domains (#PCDATA | domains)*>
<!ATTLIST local_domains config:type CDATA #IMPLIED>
<!ELEMENT min_hsync (#PCDATA)>
<!ATTLIST min_hsync config:type CDATA #IMPLIED>
<!ELEMENT height (#PCDATA)>
<!ATTLIST height config:type CDATA #IMPLIED>
<!ELEMENT domain (#PCDATA)>
<!ELEMENT nameservers (#PCDATA | nameserver)*>
<!ATTLIST nameservers config:type CDATA #IMPLIED>
<!ELEMENT kdm_shutdown (#PCDATA)>
<!ELEMENT uri (#PCDATA)>
<!ELEMENT packages (#PCDATA | package)*>
<!ATTLIST packages config:type CDATA #IMPLIED>
<!ELEMENT init (#PCDATA | domain | gateway | info_file | instmode | ip | nameserver | netmask | port | profile_location | profile_port | profile_protocol | profile_server | server | serverdir | textmode | usedhcp)*>
<!ELEMENT model (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT broadcast (#PCDATA)>
<!ELEMENT min_vsync (#PCDATA)>
<!ATTLIST min_vsync config:type CDATA #IMPLIED>
<!ELEMENT partitioning (#PCDATA | drive)*>
<!ATTLIST partitioning config:type CDATA #IMPLIED>
<!ELEMENT usedhcp (#PCDATA)>
<!ATTLIST usedhcp config:type CDATA #IMPLIED>
<!ELEMENT pass_min_days (#PCDATA)>
<!ELEMENT profile_server (#PCDATA)>
<!ELEMENT users (#PCDATA | user)*>
<!ATTLIST users config:type CDATA #IMPLIED>
<!ELEMENT option_str (#PCDATA)>
<!ELEMENT start_nfsserver (#PCDATA)>
<!ATTLIST start_nfsserver config:type CDATA #IMPLIED>
<!ELEMENT nfs_export (#PCDATA | allowed | mountpoint)*>
<!ELEMENT interface (#PCDATA | bootproto | broadcast | device | dhclient_set_down_link | ipaddr | module | netmask | network | options | startmode | wireless | wireless_essid | wireless_key | wireless_mode | wireless_nick | wireless_nwid)*>
<!ELEMENT crypt_fs (#PCDATA)>
<!ATTLIST crypt_fs config:type CDATA #IMPLIED>
<!ELEMENT bandwidth (#PCDATA)>
<!ATTLIST bandwidth config:type CDATA #IMPLIED>
<!ELEMENT volume_entry (#PCDATA | Master)*>
<!ELEMENT domains (#PCDATA)>

=== Deadmau8772/yast-autoinstallation/test_xml/part_pre-script.xml
<?xml version="1.0"?>
<!DOCTYPE profile SYSTEM "/usr/share/autoinstall/dtd/profile.dtd">
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
    <networking>
      <dns>
        <dhcp_hostname config:type="boolean">true</dhcp_hostname>
        <dhcp_resolv config:type="boolean">true</dhcp_resolv>
      </dns>
      <interfaces config:type="list">
        <interface>
          <bootproto>dhcp</bootproto>
          <device>eth0</device>
          <name>Ethernet Network Card</name>
          <startmode>auto</startmode>
          <usercontrol>no</usercontrol>
        </interface>
      </interfaces>
      <modules config:type="list">
        <module_entry>
          <device>static-0</device>
          <module></module>
          <options></options>
        </module_entry>
      </modules>
      <routing>
        <ip_forward config:type="boolean">false</ip_forward>
      </routing>
    </networking>
  <!--
    <software>
      <base>Min</base>
    </software>
    -->
     <software>
       <base>default</base>
     </software>
    <users config:type="list">
      <user>
        <encrypted config:type="boolean">true</encrypted>
        <user_password>pw</user_password>
        <username>root</username>
      </user>
    </users>
    <scripts>
        <pre-scripts config:type="list">
        <script>
                <filename>pre</filename>
                <interpreter>shell</interpreter>
                <location></location>
                <feedback config:type="boolean">true</feedback>
                <debug config:type="boolean">false</debug>
                <source><![CDATA[
echo "hda1 - kept"
cho "this is stderr"
echo "hda2 - removed and 2 new ones are created"
DEVICE="hda";
parted --script /dev/${DEVICE} rm 2
echo -e "n\n p\n 2\n\n +10G\n n\n p\n 3\n\n\n w\n" | fdisk /dev/$DEVICE
                ]]></source> 
        </script>
        </pre-scripts>
    </scripts>
  <partitioning config:type="list">
      <drive>
        <device>/dev/hda</device>
        <initialize config:type="boolean">false</initialize>
        <partitions config:type="list">
          <partition>
            <filesystem config:type="symbol">ext3</filesystem>
            <format config:type="boolean">true</format>
            <mount>/</mount>
            <partition_id config:type="integer">131</partition_id>
            <partition_type>primary</partition_type>
            <size>3513M</size>
          </partition>
          <partition>
            <format config:type="boolean">true</format>
            <partition_id config:type="integer">253</partition_id>
            <partition_type>primary</partition_type>
            <size>max</size>
          </partition>
        </partitions>
        <use>all</use>
      </drive>
  </partitioning>
</profile>

=== Deadmau8772/yast-autoinstallation/test_xml/part_fstab.xml
<?xml version="1.0"?>
<!DOCTYPE profile SYSTEM "/usr/share/autoinstall/dtd/profile.dtd">
<profile xmlns="http://www.suse.com/1.0/yast2ns" xmlns:config="http://www.suse.com/1.0/configns">
  <configure>
    <sound>
      <autoinstall config:type="boolean">true</autoinstall>
      <configure_detected config:type="boolean">true</configure_detected>
    </sound>
    <networking>
      <dns>
        <dhcp_hostname config:type="boolean">true</dhcp_hostname>
        <dhcp_resolv config:type="boolean">true</dhcp_resolv>
        <domain>aaa.cc</domain>
        <hostname>aaa</hostname>
      </dns>
      <interfaces config:type="list">
        <interface>
          <bootproto>dhcp</bootproto>
          <device>eth0</device>
          <name>Ethernet Network Card</name>
          <startmode>auto</startmode>
          <usercontrol>no</usercontrol>
        </interface>
      </interfaces>
      <modules config:type="list">
        <module_entry>
          <device>static-0</device>
          <module></module>
          <options></options>
        </module_entry>
      </modules>
      <routing>
        <ip_forward config:type="boolean">false</ip_forward>
      </routing>
    </networking>
  </configure>
  <install>
    <partitioning_advanced>
      <fstab>
    <!-- Read data from existing fstab. If multiple root partitions are
    found, use the one specified below. Otherwise the first root
    partition is taken -->
<!--    <root_partition>/dev/sda2</root_partition> -->
    <use_existing_fstab config:type="boolean">true</use_existing_fstab>
    <!-- all partitions found in fstab will be formatted and mounted
    by default unless a partition is listed below with different
    settings -->
    <partitions config:type="list">
      <partition>
        <create config:type="boolean">true</create>
        <format config:type="boolean">true</format>
        <mount>swap</mount>
      </partition>
      <partition>
        <format config:type="boolean">true</format>
        <mount>/</mount>
      </partition>
    </partitions>
      </fstab>
    </partitioning_advanced>
    <software>
<!--      <base>Min</base> -->
    </software>
    <users config:type="list">
      <user>
        <encrypted config:type="boolean">true</encrypted>
        <user_password>pw</user_password>
        <username>root</username>
      </user>
    </users>
  </install>
</profile>
